[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[[edge_functions]]
  path = "/api/*"
  function = "index"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
